version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly" # Less frequent
    open-pull-requests-limit: 2 # Fewer PRs
    commit-message:
      prefix: "deps" # Clean commit history
